// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquadEstoque.Web.Data;

#nullable disable

namespace SquadEstoque.Web.Migrations.Estoque
{
    [DbContext(typeof(EstoqueContext))]
    [Migration("20260817120442_InitialSquadSchema")]
    partial class InitialSquadSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("SquadEstoque.Web.Models.Movimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SkuId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Movimentacao", t =>
                        {
                            t.HasCheckConstraint("chk_movimentacao_quantidade_positiva", "Quantidade > 0");
                        });
                });

            modelBuilder.Entity("SquadEstoque.Web.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("SquadEstoque.Web.Models.Ruptura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SkuId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ruptura");
                });

            modelBuilder.Entity("SquadEstoque.Web.Models.Sku", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Numeracao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SaldoAtual")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId", "Numeracao")
                        .IsUnique();

                    b.ToTable("Sku", t =>
                        {
                            t.HasCheckConstraint("chk_sku_saldo_nao_negativo", "SaldoAtual >= 0");
                        });
                });

            modelBuilder.Entity("SquadEstoque.Web.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Perfil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SquadEstoque.Web.Models.Movimentacao", b =>
                {
                    b.HasOne("SquadEstoque.Web.Models.Sku", "Sku")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SquadEstoque.Web.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sku");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SquadEstoque.Web.Models.Ruptura", b =>
                {
                    b.HasOne("SquadEstoque.Web.Models.Sku", "Sku")
                        .WithMany("Rupturas")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SquadEstoque.Web.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sku");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SquadEstoque.Web.Models.Sku", b =>
                {
                    b.HasOne("SquadEstoque.Web.Models.Produto", "Produto")
                        .WithMany("Skus")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SquadEstoque.Web.Models.Produto", b =>
                {
                    b.Navigation("Skus");
                });

            modelBuilder.Entity("SquadEstoque.Web.Models.Sku", b =>
                {
                    b.Navigation("Movimentacoes");

                    b.Navigation("Rupturas");
                });
#pragma warning restore 612, 618
        }
    }
}
